mongodb:                                                                                                                                                                      
    server:   localhost                                                           
    database: dashboard                                                           
    user: root                                                                    
    password:
